name: Main

on:
  push:
    paths:
      - tesina.md
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Italy Time
        id: italy_time
        run: |
          TZ="Europe/Rome"  # Set the time zone to Italy
          ITALY_TIME=$(date "+%Y-%m-%d-%H-%M-%S")
          echo "::set-output name=italy_time::$ITALY_TIME"

      - name: Install Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.14/pandoc-2.14-1-amd64.deb
          sudo dpkg -i pandoc-2.14-1-amd64.deb
      - name: Create dist dir
        run: |
          mkdir ./dist
      - name: Generate tesina.docx
        run: |
          out_name="./dist/tesina-${{ steps.italy_time.outputs.italy_time }}.docx"
          pandoc tesina.md -o ${out_name}
      - name: Add other files to dist
        run: |
          out_name="./dist/tesina-${{ steps.italy_time.outputs.italy_time }}.md"
          mv tesina.md ${out_name}
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
          tag_name: revisione-${{ steps.italy_time.outputs.italy_time }}
          name: revisione-${{ steps.italy_time.outputs.italy_time }}
